services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - school_net
    restart: always
    command: >
      tunnel --no-autoupdate run
      --token eyJhIjoiZjRkZDVkNzA0MTJlMTA1MDhkZjM4ZjQwNDEzMDM0ODciLCJ0IjoiNzRjMzcwNGUtNjk5NC00MzYwLTk5ZDYtYmE1ZGI0MmIwN2IzIiwicyI6IlpEZGtOekV6WmpndFlUWmpPUzAwWkRRMExUaGlOamd0WmpsaFpqWTFNR001WkdRdyJ9

networks:
  school_net:
    name: school_net
#docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiZjRkZDVkNzA0MTJlMTA1MDhkZjM4ZjQwNDEzMDM0ODciLCJ0IjoiNzRjMzcwNGUtNjk5NC00MzYwLTk5ZDYtYmE1ZGI0MmIwN2IzIiwicyI6IlpEZGtOekV6WmpndFlUWmpPUzAwWkRRMExUaGlOamd0WmpsaFpqWTFNR001WkdRdyJ9
